[package]
name = "sequence_visualizer"
version = "0.1.0"
authors = ["Gert Kanter"]
edition = "2021"

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
json = "0.12.4"
plotpy="0.3.5"

